#!/bin/bash
# -*- coding:utf-8 -*-
# Name:      baidu
# Usage:     v1.0 在终端中调用chrome直接百度，参数是要百度的内容
#            因为只是方便自己用的，所以没有做浏览器检查什么的
#            v1.1 update the order by 'browser' which can choose another
#            browser if my os doesn't have chrome or firefox
# Example:   baidu haha woshiyigedashabi
# Author:    andy (andy.at.working@gmail.com)
# Version:   1.1
# Date:      Jul 2 2014
# Base:      browser(1.0)


data="$@"
browser www.baidu.com/#wd="${data}" 1> /dev/null 2> /dev/null &
