#!/bin/bash

if [ -z "$1" ];then
	echo ""
	echo "  Please tell me the name of remote repository name"
	echo ""
	exit
fi

a=`find . -name .git`

if [ -n "$a" ];then
	# There is .git/ in current directory
	echo "  I find you have initialize your repository."
	echo "  Do you want to remove .git/ and create a new one?(yes/NO)"
	read answer
	if [[ $answer = [Yy][Ee][Ss] || $answer = [Yy] ]];then
		rm -rf .git/
	else
		exit
	fi
fi

git init
git config --global user.name Andy
git config --global user.email Andy.at.working@gmail.com
git add .
git commit -m 'init'
git remote add local ssh://Andy@192.168.135.14/volume1/git_repos/Andy/$1
while true;
do
	git push local master
	b=`echo "$?"`
	echo "$b"
	if [ "$b" -eq "0" ];then
		# Push successfully.
		echo ""
		echo "  Congratulations, initialize git repository successfully."
		echo ""
		exit
	elif [ "$b" -eq "1" ];then
		# Maybe this is a problem about merge.
		# You can try to pull first and then push.
		echo ""
		echo "  There was something wrong when you push your code."
		echo "  Maybe we need to pull the code from remote repository first"
		echo "  Do you want to pull the code?(yes/NO)"
		read answer
		if [[ $answer = [Yy][Ee][Ss] || $answer = [Yy] ]];then
			# You choose pull the code.
			git pull local master
			c=`echo "$?"`
			if [ "$c" -ne "0" ];then
				# Pull failed.
				echo ""
				echo "  There was something wrong when you pull your code."
				echo "  Do you need to remove .git/ and exit?(yes/NO)"
				read answer
				if [[ $answer = [Yy][Ee][Ss] || $answer = [Yy] ]];then
					rm -rf .git/
				fi
				exit
			fi
			# Pull successfully and try to push again.
		else
			# You don't want to pull, and I don't know what I can do.
			# So game over.
			echo ""
			echo "  Do you need to remove .git/ and exit?(yes/NO)"
			read answer
			if [[ $answer = [Yy][Ee][Ss] || $answer = [Yy] ]];then
				rm -rf .git/
			fi
			exit
		fi
	else
		# I don't know what's wrong about this push, so game over.
		echo ""
		echo "  There was something wrong when you push your code."
		echo "  Do you need to remove .git/ and exit?(yes/NO)"
		read answer
		if [[ $answer = [Yy][Ee][Ss] || $answer = [Yy] ]];then
			rm -rf .git/
		fi
		exit
	fi
done
