#!/bin/bash
# -*- coding:utf-8 -*-
# Name:      timer
# Usage:     在终端中调用开一个定时器，在一定时间之后在屏幕右上方弹出通知
#            消息提醒。因为只是方便自己用的，所以用的ubuntu下的notify-send
#            命令不知道在其他系统中是否也有
# Author:    andy (andy.at.working@gmail.com)
# Version:   1.0
# Date:      Apr 12 2014

(sleep $@ 1> /dev/null ; notify-send "Hey, do you forget something?" 1> /dev/null 2> /dev/null ) &

