#!/bin/bash
# -*- coding:utf-8 -*-
# Name:      install-packets
# Usage:     重装完系统之后,虽然home分区有单独挂载,但是软件该重装的还是要重装的
# Example:   ./install-packets
# Author:    andy (andy.at.working@gmail.com)
# Version:   1.0
# Date:      Apr 19 2014
# Comment:   在运行之前请先更改软件源为中科大,没有什么原因,只是个人习惯 =.=
#            为了防止误操作,所以文件没有执行权限
#            terminator和字典的配置文件都备份本文件夹下了
#            flash-plugin : https://wiki.ubuntu.com/Chromium/Getting-Flash

sudo apt-get update 
sudo apt-get upgrade 
# for my terminal
sudo apt-get -y install terminator
# for chrome
sudo apt-get -y install chromium-browser
# for dict
sudo apt-get -y install sdcv
sudo ln /usr/bin/sdcv /usr/bin/dict
# for using vi
sudo apt-get -y install vim
# for coding C
sudo apt-get -y install ctags
# for markdown to html
sudo apt-get -y install pandoc
# for github
sudo apt-get -y install git
# for goagent
sudo apt-get -y install python-dev python-greenlet python-gevent python-vte python-openssl python-crypto python-appindicator
sudo apt-get -y install python-dev python-pip && sudo pip install gevent --upgrade
# for wiznote
sudo  add-apt-repository ppa:wiznote-team
sudo apt-get update
sudo apt-get -y install wiznote
# for gimp
sudo apt-get -y install gimp
