#!/bin/bash
# -*- coding:utf-8 -*-
# Name:      goagent
# Usage:     退出goagent
# Example:   goagent-exit
# Author:    andy (andy.at.working@gmail.com)
# Version:   1.0
# Date:      Apr 19 2014

sudo ps aux|grep proxy.py|grep -v "grep"|awk '{print $2}'|xargs kill
